/* -*- mode: c++; indent-tabs-mode: nil -*- */
/** @file nats-module.h nats module header file */
/*
    Qore nats module

    Copyright (C) 2026 Qore Technologies, s.r.o.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef _QORE_NATS_MODULE_H
#define _QORE_NATS_MODULE_H

#include <qore/Qore.h>
#include <qore/QoreSandboxManager.h>
#include <qore/qore_thread.h>

#include <nats/nats.h>

// Forward declarations
class QoreNatsConnection;
class QoreNatsSubscription;
class QoreNatsJetStream;
class QoreNatsKVStore;
class QoreNatsKVWatcher;
class QoreNatsMicroService;
class QoreNatsMicroGroup;

// Hashdecl init functions (generated by QPP)
DLLLOCAL TypedHashDecl* init_hashdecl_NatsTlsOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsConnectionOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsMsgInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsStreamConfig(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsConsumerConfig(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsStreamInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsConsumerInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsPubAck(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsKVConfig(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsKVEntry(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsConnectionStats(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsConnectionInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsJSMsgMetadata(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsJSPubOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsJSAccountLimits(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsJSAccountInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsJSSubOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsSubscriptionStats(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsKVBucketStatus(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsKVWatchOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsMicroEndpointConfig(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsMicroServiceConfig(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsMicroEndpointInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsMicroServiceInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsMicroEndpointStats(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_NatsMicroServiceStats(QoreNamespace& ns);

// Global hashdecl pointers (initialized in nats-module.cpp)
extern const TypedHashDecl* hashdeclNatsTlsOptions;
extern const TypedHashDecl* hashdeclNatsConnectionOptions;
extern const TypedHashDecl* hashdeclNatsMsgInfo;
extern const TypedHashDecl* hashdeclNatsStreamConfig;
extern const TypedHashDecl* hashdeclNatsConsumerConfig;
extern const TypedHashDecl* hashdeclNatsStreamInfo;
extern const TypedHashDecl* hashdeclNatsConsumerInfo;
extern const TypedHashDecl* hashdeclNatsPubAck;
extern const TypedHashDecl* hashdeclNatsKVConfig;
extern const TypedHashDecl* hashdeclNatsKVEntry;
extern const TypedHashDecl* hashdeclNatsConnectionStats;
extern const TypedHashDecl* hashdeclNatsConnectionInfo;
extern const TypedHashDecl* hashdeclNatsJSMsgMetadata;
extern const TypedHashDecl* hashdeclNatsJSPubOptions;
extern const TypedHashDecl* hashdeclNatsJSAccountLimits;
extern const TypedHashDecl* hashdeclNatsJSAccountInfo;
extern const TypedHashDecl* hashdeclNatsJSSubOptions;
extern const TypedHashDecl* hashdeclNatsSubscriptionStats;
extern const TypedHashDecl* hashdeclNatsKVBucketStatus;
extern const TypedHashDecl* hashdeclNatsKVWatchOptions;
extern const TypedHashDecl* hashdeclNatsMicroEndpointConfig;
extern const TypedHashDecl* hashdeclNatsMicroServiceConfig;
extern const TypedHashDecl* hashdeclNatsMicroEndpointInfo;
extern const TypedHashDecl* hashdeclNatsMicroServiceInfo;
extern const TypedHashDecl* hashdeclNatsMicroEndpointStats;
extern const TypedHashDecl* hashdeclNatsMicroServiceStats;

// Class init functions (generated by QPP)
DLLLOCAL QoreClass* initNatsConnectionClass(QoreNamespace& ns);
DLLLOCAL QoreClass* initNatsSubscriptionClass(QoreNamespace& ns);
DLLLOCAL QoreClass* initJetStreamContextClass(QoreNamespace& ns);
DLLLOCAL QoreClass* initNatsKeyValueWatcherClass(QoreNamespace& ns);
DLLLOCAL QoreClass* initNatsKeyValueStoreClass(QoreNamespace& ns);
DLLLOCAL QoreClass* initNatsMicroServiceClass(QoreNamespace& ns);
DLLLOCAL QoreClass* initNatsMicroGroupClass(QoreNamespace& ns);

// Class pointers
extern QoreClass* QC_NATSCONNECTION;
extern qore_classid_t CID_NATSCONNECTION;
extern QoreClass* QC_NATSSUBSCRIPTION;
extern qore_classid_t CID_NATSSUBSCRIPTION;
extern QoreClass* QC_JETSTREAMCONTEXT;
extern qore_classid_t CID_JETSTREAMCONTEXT;
extern QoreClass* QC_NATSKEYVALUEWATCHER;
extern qore_classid_t CID_NATSKEYVALUEWATCHER;
extern QoreClass* QC_NATSKEYVALUESTORE;
extern qore_classid_t CID_NATSKEYVALUESTORE;
extern QoreClass* QC_NATSMICROSERVICE;
extern qore_classid_t CID_NATSMICROSERVICE;
extern QoreClass* QC_NATSMICROGROUP;
extern qore_classid_t CID_NATSMICROGROUP;

// Namespace
extern QoreNamespace NatsNs;

#endif // _QORE_NATS_MODULE_H
